### ISSUE TITLE
information request - preguntas sobre el lua bot

### ISSUE THREAD

**Issue by mckaygerhard** [iicc1/AutoPoleTelegramBot#1]
hablas espan asi que pregunto sobre el codigo:

* para que usar el redis, una explicacion de porque no directo al API?
* en la linea 9 se establece la hora fija, pero pregunta al redis por eso la primera pregunta

Esta ultima, el lua es muy bueno por su simplicidad y claridad pero el proceso para instalarlo parece sacado de uan pelicula de terror, con dependencias rebuscadas..

**Comment by iicc1** [comment]
Cuando desarrollé este bot me encontré con problemas muy curiosos con TDCLI, por eso algunas cosas parecen rebuscadas.
Resulta que en TDCLI no se podía enviar un mensaje cuando quisieras, solo podías enviar cuando recibías una update.
Entonces, lo que hace el bot es esperar a que llegue un mensaje cuando sean las 00:00 pasadas y enviar el mensaje a todos los chats. El Redis ahí hace de cooldown, cuando haya enviado todos los mensajes, esperate 10 segundos antes de volver a comprobar. Después de enviar esos mensajes ya no entraría en el match de la hora y así solo podrían volver a enviarse los mensajes al día siguiente.

Es algo rebuscado la verdad, con una especie de sleep habría bastado.
De todas formas yo ahora no usaría TDCLI, está obsoleto. Recomiendo Telethon.

**Comment by mckaygerhard** [comment]
Excelente, gracias, muy consiso.. revisare Telethon aunque recuerdo que es python pero que mas da..
